
[general]
GOOGLE_API_KEY = "AIzaSyBjWsS1SXyEhhQIz1V4d6t2SpnEmU_Fu74"
AGROMONITOR_API="b5f9a3d4-2e47-4a5e-8d7c-6f1a9b0e2d8d"  # (example) Crop monitoring API
WEATHER_API_KEY="c7e4a9f8-3b1c-4d2e-8f5a-1b0e3d7c6f2a"  # (example) Weather data
